### ISSUE TITLE
NoSuchMethodError (ChangesBrowser.getDiffAction()) in EAP (IU-140.2493.5)

### ISSUE THREAD

**Issue by talanb** [ktisha/Crucible4IDEA#68]
Got the following stacktrace after double clicking on a review in my list.

```
2015-02-19 11:49:39,779 [ 273638]  ERROR - pplication.impl.LaterInvocator - com.intellij.openapi.vcs.changes.ui.ChangesBrowser.getDiffAction()Lcom/intellij/openapi/vcs/changes/actions/ShowDiffAction; 
java.lang.NoSuchMethodError: com.intellij.openapi.vcs.changes.ui.ChangesBrowser.getDiffAction()Lcom/intellij/openapi/vcs/changes/actions/ShowDiffAction;
	at com.jetbrains.crucible.ui.toolWindow.details.DetailsPanel.createRepositoryBrowserDetails(DetailsPanel.java:213)
	at com.jetbrains.crucible.ui.toolWindow.details.DetailsPanel.<init>(DetailsPanel.java:70)
	at com.jetbrains.crucible.ui.toolWindow.CruciblePanel.openDetailsToolWindow(CruciblePanel.java:139)
	at com.jetbrains.crucible.ui.toolWindow.CruciblePanel$1$1.run(CruciblePanel.java:87)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:741)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:576)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:383)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
2015-02-19 11:49:39,780 [ 273639]  ERROR - pplication.impl.LaterInvocator - IntelliJ IDEA (Cassiopeia) IU-140.2493.5  Build #IU-140.2493.5 
2015-02-19 11:49:39,780 [ 273639]  ERROR - pplication.impl.LaterInvocator - JDK: 1.7.0_60 
2015-02-19 11:49:39,780 [ 273639]  ERROR - pplication.impl.LaterInvocator - VM: Java HotSpot(TM) 64-Bit Server VM 
2015-02-19 11:49:39,781 [ 273640]  ERROR - pplication.impl.LaterInvocator - Vendor: Oracle Corporation 
2015-02-19 11:49:39,781 [ 273640]  ERROR - pplication.impl.LaterInvocator - OS: Linux 
2015-02-19 11:49:39,781 [ 273640]  ERROR - pplication.impl.LaterInvocator - Last Action: ShowSettings 
2015-02-19 11:49:59,384 [ 293243]   INFO - ework.TestFileStructureManager - JsTestDriver: Creating TestFileStructurePack for jquery.js took 69.71 ms 
2015-02-19 11:50:07,728 [ 301587]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update done in 202741 ms 
2015-02-19 11:50:08,006 [ 301865]   INFO - lij.tasks.impl.TaskManagerImpl - Login failed. Enter captcha in web-interface. 
java.lang.Exception: Login failed. Enter captcha in web-interface.
	at com.intellij.tasks.jira.JiraRepository.executeMethod(JiraRepository.java:292)
	at com.intellij.tasks.jira.JiraRepository.discoverApiVersion(JiraRepository.java:189)
	at com.intellij.tasks.jira.JiraRepository.ensureApiVersionDiscovered(JiraRepository.java:238)
	at com.intellij.tasks.jira.JiraRepository.findTask(JiraRepository.java:151)
	at com.intellij.tasks.impl.TaskManagerImpl.updateIssue(TaskManagerImpl.java:298)
	at com.intellij.tasks.impl.TaskManagerImpl$9$1.run(TaskManagerImpl.java:496)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:405)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

**Comment by southpawlife** [comment]
Any news on this one? I am seeing the same thing running 14.1.

**Comment by ktisha** [comment]
Updated plugin on plugins.jetbrains.com
