### ISSUE TITLE
Malformed Json

### ISSUE THREAD

**Issue by josuehenrique** [ktisha/Crucible4IDEA#77]
Occurred when i tried fill username and password in settings.

`Malformed Json
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at com.jetbrains.crucible.connection.CrucibleSessionImpl.buildJsonResponse(CrucibleSessionImpl.java:160)
	at com.jetbrains.crucible.connection.CrucibleSessionImpl.login(CrucibleSessionImpl.java:92)
	at com.jetbrains.crucible.connection.CrucibleTestConnector.testConnect(CrucibleTestConnector.java:70)
	at com.jetbrains.crucible.connection.CrucibleTestConnector.run(CrucibleTestConnector.java:37)
	at com.jetbrains.crucible.connection.CrucibleTestConnectionTask.run(CrucibleTestConnectionTask.java:32)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:357)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl$14$1.run(ApplicationImpl.java:626)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
`

**Comment by JoyJava** [comment]
Have you done it?
