### ISSUE TITLE
TestConnection Error , the Exception Message

### ISSUE THREAD

**Issue by JoyJava** [ktisha/Crucible4IDEA#79]
Malformed Json
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at com.jetbrains.crucible.connection.CrucibleSessionImpl.buildJsonResponse(CrucibleSessionImpl.java:160)
	at com.jetbrains.crucible.connection.CrucibleSessionImpl.login(CrucibleSessionImpl.java:92)
	at com.jetbrains.crucible.connection.CrucibleTestConnector.testConnect(CrucibleTestConnector.java:70)
	at com.jetbrains.crucible.connection.CrucibleTestConnector.run(CrucibleTestConnector.java:37)
	at com.jetbrains.crucible.connection.CrucibleTestConnectionTask.run(CrucibleTestConnectionTask.java:32)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:357)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl$14$1.run(ApplicationImpl.java:634)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)

**Comment by kernixski** [comment]
Same problem for me with IDEA 2016.1.3 and plugin 0.5.4:

```
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.jetbrains.crucible.connection.CrucibleSessionImpl.buildJsonResponse(CrucibleSessionImpl.java:161)
	at com.jetbrains.crucible.connection.CrucibleSessionImpl.login(CrucibleSessionImpl.java:92)
	at com.jetbrains.crucible.connection.CrucibleTestConnector.testConnect(CrucibleTestConnector.java:70)
	at com.jetbrains.crucible.connection.CrucibleTestConnector.run(CrucibleTestConnector.java:37)
	at com.jetbrains.crucible.connection.CrucibleTestConnectionTask.run(CrucibleTestConnectionTask.java:32)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:357)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl$13$1.run(ApplicationImpl.java:633)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by kermek** [comment]
Same for IntelliJ IDEA 2016.2.4
Build #IC-162.2032.8, built on September 9, 2016
JRE: 1.8.0_45-b15 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

**Comment by fedorov-s-n** [comment]
Same for 2017.1.5

**Comment by JanGalek** [comment]
same for 2019.1.2

**Comment by julieagreen** [comment]
same 2019.2.4
