### ISSUE TITLE
Can't open any review

### ISSUE THREAD

**Issue by sbojchuk** [ktisha/Crucible4IDEA#80]
List of code reviews loaded successfully from Crucible, but when trying to open any, exception is occurred.

`com.intellij.openapi.vcs.changes.ui.ChangesBrowser.getDiffAction()Lcom/intellij/openapi/vcs/changes/actions/diff/ShowDiffAction;
java.lang.NoSuchMethodError: com.intellij.openapi.vcs.changes.ui.ChangesBrowser.getDiffAction()Lcom/intellij/openapi/vcs/changes/actions/diff/ShowDiffAction;
	at com.jetbrains.crucible.ui.toolWindow.details.DetailsPanel.createRepositoryBrowserDetails(DetailsPanel.java:214)
	at com.jetbrains.crucible.ui.toolWindow.details.DetailsPanel.<init>(DetailsPanel.java:71)
	at com.jetbrains.crucible.ui.toolWindow.CruciblePanel.openDetailsToolWindow(CruciblePanel.java:139)
	at com.jetbrains.crucible.ui.toolWindow.CruciblePanel$1$1.run(CruciblePanel.java:87)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:863)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by michalsvec** [comment]
I guess you're not using git, right?

**Comment by sbojchuk** [comment]
yes, you're right

**Comment by michalsvec** [comment]
I use perforce and have the same problem. Issue is, that there's ONLY git support hardcoded.

**Comment by sbojchuk** [comment]
oh... :disappointed:

**Comment by jonathanvila** [comment]
This is happening to me also, and I'm using GIT
Do I have to configure GIT in a certain way ? configure IntelliJ ?

**Comment by shaun-w** [comment]
I'm also using git and have the same problem

**Comment by geeves** [comment]
Same problem.  Using git 2.8.4 and IntelliJ 2016.2

**Comment by mmbradle** [comment]
+1
Using git and IntelliJ 2016.2

**Comment by olegvasylenko** [comment]
+1
Using git 2.10.1
IntelliJ IDEA 2016.3.4
Build #IU-163.12024.16, built on January 31, 2017
JRE: 1.8.0_101-b13 amd64

**Comment by giampaolotorresi** [comment]
same problem with webstorm 2017.1
